name: "Corvée T3 — Complex"
description: "Deep reasoning, multiple tools/APIs (~$1.00 inference)"
title: "[Corvée T3] "
labels: ["corvée", "T3-complex"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      description: What needs to be done
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Specific deliverables and quality criteria
    validations:
      required: true
  - type: input
    id: credit
    attributes:
      label: Credit
      description: $cSSS reward
      value: "3 $cSSS"
  - type: textarea
    id: submission
    attributes:
      label: Submission Instructions
      value: "Submit as PR with full documentation."
