name: "Corvée T2 — Standard"
description: "Multi-step task, moderate complexity (~$0.30 inference)"
title: "[Corvée T2] "
labels: ["corvée", "T2-standard"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      description: What needs to be done
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Specific deliverables and quality criteria
    validations:
      required: true
  - type: input
    id: credit
    attributes:
      label: Credit
      description: $cSSS reward
      value: "2 $cSSS"
  - type: textarea
    id: submission
    attributes:
      label: Submission Instructions
      value: "Submit as PR with output in corvee-output/."
